#include "DigBCD.hpp"

typedef basic_string<DigBCD> BasicNumB10Str;

class ParBCD : protected N2DigsBCD {
		friend istream & operator >> (istream &,ParBCD);
		friend ostream & operator << (ostream &,ParBCD);
	public:
		ParBCD(); 
		ParBCD(DigBCD,DigBCD);
		ParBCD(const N2DigsBCD &);
		explicit ParBCD(N2DigsBCD &);
		ParBCD(uchint,uchint);
		ParBCD(char,char);
		ParBCD(const string &);
		ParBCD(int,int);
		ParBCD(const ParBCD &);
		explicit ParBCD(ParBCD &); 
		const ParBCD & operator = (const ParBCD &);
		ParBCD & operator = (ParBCD &);
		operator DigBCD() const;
		bool operator == (ParBCD) const;
		bool operator != (ParBCD) const;
		bool operator <= (ParBCD) const;
		bool operator >= (ParBCD) const;
		bool operator <  (ParBCD) const;
		bool operator >  (ParBCD) const;
		ParBCD operator + (const ParBCD &) const;
		ParBCD operator - (const ParBCD &) const;
		ParBCD operator * (const ParBCD &) const;
		ParBCD operator / (const ParBCD &) const;
		ParBCD operator % (const ParBCD &) const;
		const ParBCD & operator += (const ParBCD &);
		const ParBCD & operator -= (const ParBCD &);
		const ParBCD & operator *= (const ParBCD &);
		const ParBCD & operator /= (const ParBCD &);
		const ParBCD & operator %= (const ParBCD &);
		operator usint () const; 
		ParBCD operator -  () const; 
		ParBCD operator !  () const; 
		const ParBCD & mC10  (); 
		const ParBCD & mC9   (); 
		const ParBCD & operator ++ ();
		ParBCD operator ++ (int);
		const ParBCD & operator -- ();
		ParBCD operator -- (int);
		DigBCD g_second() const;
		DigBCD g_first() const;
		void p_second(DigBCD);
		void p_first(DigBCD);
		ParBCD operator +  (DigBCD) const;
		ParBCD operator -  (DigBCD) const;
		ParBCD operator *  (DigBCD) const;
		ParBCD operator /  (DigBCD) const;
		ParBCD operator %  (DigBCD) const;
		const ParBCD & operator += (DigBCD);
		const ParBCD & operator -= (DigBCD);
		const ParBCD & operator *= (DigBCD);
		const ParBCD & operator /= (DigBCD);
		const ParBCD & operator %= (DigBCD);
		ParBCD operator +  (const N2DigsBCD &) const;
		ParBCD operator -  (const N2DigsBCD &) const;
		ParBCD operator *  (const N2DigsBCD &) const;
		ParBCD operator /  (const N2DigsBCD &) const;
		ParBCD operator %  (const N2DigsBCD &) const;
		const ParBCD & operator += (const N2DigsBCD &);
		const ParBCD & operator -= (const N2DigsBCD &);
		const ParBCD & operator *= (const N2DigsBCD &);
		const ParBCD & operator /= (const N2DigsBCD &);
		const ParBCD & operator %= (const N2DigsBCD &);
	};

istream & operator >> (istream & in,ParBCD arg);
ostream & operator << (ostream & on,ParBCD arg);
